services:
  - type: web
    name: phishguard-api
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn --chdir backend app:app
    envVars:
      - key: PHISHGUARD_API_KEY
        generateValue: true

  - type: web
    name: phishguard-frontend
    runtime: static
    buildCommand: python replace_api_url.py
    staticPublishPath: ./frontend
    envVars:
      - key: PHISHGUARD_API_URL
        fromService:
          type: web
          name: phishguard-api
          envVarKey: RENDER_EXTERNAL_URL
      - key: PHISHGUARD_API_KEY
        fromService:
          type: web
          name: phishguard-api
          envVarKey: PHISHGUARD_API_KEY
